import type { RankedCandidate } from "../schemas/ranked-candidate";
import type { Candidate } from "../schemas/candidate";
import type { DraftResult } from "../schemas/draft";
import type { Critique } from "../schemas/critique";
import { logger } from "../utils/logger";

export async function generateDigest(
  rankedCandidates: RankedCandidate[],
  candidates: Candidate[],
  draftResults: DraftResult[],
  critiques: Critique[],
  profile: string,
  niche: string,
  date: string
): Promise<string> {
  logger.step(7, 7, "Generating digest");

  const lines: string[] = [];

  lines.push(`# Content Digest: ${date}`);
  lines.push(`## Profile: ${profile} | Niche: ${niche}`);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Top Topics");
  lines.push("");

  let totalDrafts = 0;
  let recommendedCount = 0;

  for (let i = 0; i < rankedCandidates.length; i++) {
    const ranked = rankedCandidates[i];
    const candidate = candidates.find((c) => c.id === ranked.candidateId);
    const draftResult = draftResults.find((d) => d.candidateId === ranked.candidateId);

    if (!candidate) {
      continue;
    }

    lines.push(`### ${i + 1}. ${ranked.title}`);
    lines.push(`**Source**: [${candidate.sourceName}](${ranked.sourceUrl})`);
    lines.push(`**Score**: ${ranked.finalScore} — ${ranked.rankingReason}`);
    lines.push("");
    lines.push(`**Why it matters**: ${candidate.whyItMatters}`);
    lines.push(`**Audience relevance**: ${candidate.audienceRelevance}`);
    lines.push("");

    if (candidate.possibleAngles.length > 0) {
      lines.push("**Suggested angles**:");
      for (const angle of candidate.possibleAngles.slice(0, 3)) {
        lines.push(`- ${angle}`);
      }
      lines.push("");
    }

    if (draftResult && draftResult.drafts.length > 0) {
      totalDrafts += draftResult.drafts.length;

      const draftsWithCritiques = draftResult.drafts.map((draft) => {
        const critique = critiques.find(
          (c) => c.candidateId === ranked.candidateId && c.draftType === draft.type
        );

        return { draft, critique };
      });

      const best = draftsWithCritiques.reduce((a, b) => {
        const aScore = a.critique?.scores.postWorthiness ?? 0;
        const bScore = b.critique?.scores.postWorthiness ?? 0;
        return bScore > aScore ? b : a;
      });

      lines.push(`#### Best Draft (${best.draft.type})`);
      lines.push("");

      const draftLines = best.draft.content.split("\n");
      for (const line of draftLines) {
        lines.push(`> ${line}`);
      }
      lines.push("");

      if (best.critique) {
        const critique = best.critique;

        if (critique.shouldUse) {
          recommendedCount++;
        }

        lines.push("#### Critic Notes");
        if (critique.strengths.length > 0) {
          lines.push(`**Strengths**: ${critique.strengths.join("; ")}`);
        }
        if (critique.weaknesses.length > 0) {
          lines.push(`**Weaknesses**: ${critique.weaknesses.join("; ")}`);
        }
        if (critique.recommendedChanges.length > 0) {
          lines.push(
            `**Recommended changes**: ${critique.recommendedChanges.join("; ")}`
          );
        }
        lines.push(
          `**Post-worthy**: ${critique.shouldUse ? "YES" : "NO"} (score: ${critique.scores.postWorthiness}/10)`
        );
        lines.push("");
      }
    }

    if (candidate.riskNotes.length > 0) {
      lines.push("#### Risk Notes");
      for (const risk of candidate.riskNotes) {
        lines.push(`- ${risk}`);
      }
      lines.push("");
    }

    lines.push("---");
    lines.push("");
  }

  lines.push("## Summary");
  lines.push(`- Topics reviewed: ${rankedCandidates.length}`);
  lines.push(`- Drafts generated: ${totalDrafts}`);
  if (recommendedCount > 0) {
    lines.push(`- Recommended for posting: ${recommendedCount}`);
  } else {
    lines.push(
      "- No drafts recommended for posting — consider revising angles or sourcing fresher content."
    );
  }
  lines.push("");
  lines.push("---");
  lines.push("*Generated by content-harness. Human review required before posting.*");

  const digest = lines.join("\n");
  logger.success("Digest generated", `${digest.length} chars`);
  return digest;
}
